services:
  backend:
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: saas_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

volumes:
  mongo_data:
